/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author geova
 */
public class Painel_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Painel_cliente
     */
    public Painel_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_principal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDatas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListHorarios = new javax.swing.JList<>();
        jButtonAgenda = new javax.swing.JButton();
        jComboBoxCortesDisponiveis = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorCorte = new javax.swing.JTextField();
        jButtonEditaAgenda = new javax.swing.JButton();
        jButtonRemoveAgendamento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListStatusDeAgendamento = new javax.swing.JList<>();
        Funcionarios = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListDatas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datas Disponiveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jListDatas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "11/09/2024", "12/09/2024", "13/09/2024", "14/09/2024", "15/09/2024", "16/09/2024", "17/09/2024", "18/09/2024", "19/09/2024", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        Painel_principal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 125));

        jListHorarios.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horarios Disponiveis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jListHorarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListHorarios);

        Painel_principal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 200, 125));

        jButtonAgenda.setText("Agendar");
        Painel_principal.add(jButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 334, 100, -1));

        jComboBoxCortesDisponiveis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabelo", "Cabelo + Barba", "Cabelo + Barba + Sobrancelha" }));
        jComboBoxCortesDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCortesDisponiveisActionPerformed(evt);
            }
        });
        Painel_principal.add(jComboBoxCortesDisponiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 206, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cortes");
        Painel_principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Valor");
        Painel_principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jTextFieldValorCorte.setText("R$ 150,00");
        jTextFieldValorCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCorteActionPerformed(evt);
            }
        });
        Painel_principal.add(jTextFieldValorCorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 206, -1));

        jButtonEditaAgenda.setText("Editar");
        Painel_principal.add(jButtonEditaAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 334, 100, -1));

        jButtonRemoveAgendamento.setText("Remover");
        Painel_principal.add(jButtonRemoveAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 334, 100, -1));

        jListStatusDeAgendamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agendado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jListStatusDeAgendamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Data: 11/09/2024", "Hora: 09:00", "Valor: R$ 150,00" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListStatusDeAgendamento);

        Painel_principal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 10, 200, 125));

        Funcionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Joao", "Lucas", "Matheus", "Fernando" }));
        Funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosActionPerformed(evt);
            }
        });
        Painel_principal.add(Funcionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 38, 206, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cabeleleiro");
        Painel_principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCorteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorCorteActionPerformed

    private void FuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncionariosActionPerformed

    private void jComboBoxCortesDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCortesDisponiveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCortesDisponiveisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Funcionarios;
    private javax.swing.JPanel Painel_principal;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonEditaAgenda;
    private javax.swing.JButton jButtonRemoveAgendamento;
    private javax.swing.JComboBox<String> jComboBoxCortesDisponiveis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListDatas;
    private javax.swing.JList<String> jListHorarios;
    private javax.swing.JList<String> jListStatusDeAgendamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldValorCorte;
    // End of variables declaration//GEN-END:variables
}
