/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BDO.PessoaBanco;
import Controller.ClienteController;
import Model.Pessoa;
import Model.Servico;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pedro
 */
public class ViewCliente extends javax.swing.JFrame {

    private final ClienteController controller;
    private final Pessoa pessoa;
    private Color colorDefaultInicio = new Color(121,121,121);
    private Color colorDefaultAgendamento = new Color(121,121,121);
    private Color colorDefaultPerfil = new Color(121,121,121);
    


    public ViewCliente() {
        initComponents();
        controller = new ClienteController(this);
        this.pessoa = null;
        
        colorDefaultInicio = new Color(121,121,121);
        colorDefaultAgendamento = new Color(78,78,78);
        colorDefaultPerfil = new Color(78,78,78);
        jSelecionaData.setEnabled(false);
        jComboBoxHorarios.setEnabled(false);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);

    }

    public ViewCliente(Pessoa pessoa) {
        initComponents();
        controller = new ClienteController(this);
        this.pessoa = pessoa;
        jSelecionaData.setEnabled(false);
        jComboBoxHorarios.setEnabled(false);
        colorDefaultInicio = new Color(121,121,121);
        colorDefaultAgendamento = new Color(78,78,78);
        colorDefaultPerfil = new Color(78,78,78);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelBarraPrincipal = new javax.swing.JPanel();
        JPanelBtnInicio = new javax.swing.JPanel();
        jLabelIconInicio = new javax.swing.JLabel();
        jLabelTituloInicio = new javax.swing.JLabel();
        jPanelBtnAgendamento = new javax.swing.JPanel();
        jLabelIconCalendario = new javax.swing.JLabel();
        jLabelTituloAgendamento = new javax.swing.JLabel();
        jPanelBtnPerfil = new javax.swing.JPanel();
        jLabelIconPerfil = new javax.swing.JLabel();
        jLabelTituloPerfi = new javax.swing.JLabel();
        jPanelBtnSair = new javax.swing.JPanel();
        jLabelIconSair = new javax.swing.JLabel();
        jLabelTituloSair = new javax.swing.JLabel();
        jPanelBarraPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneAbas = new javax.swing.JTabbedPane();
        jPanelInicio = new javax.swing.JPanel();
        jScrollPaneAgendado = new javax.swing.JScrollPane();
        jTextAreaAgendado = new javax.swing.JTextArea();
        jPanelBtnNovoAgendamento = new javax.swing.JPanel();
        jLabelNovoAgendamento = new javax.swing.JLabel();
        jButtonNovoAgendamento = new javax.swing.JButton();
        jPanelAgendamento = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonMarcar = new javax.swing.JButton();
        jComboBoxFuncionario = new javax.swing.JComboBox<>();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jSelecionaData = new com.toedter.calendar.JDateChooser();
        jComboBoxHorarios = new javax.swing.JComboBox<>();
        jPanelPerfil = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldDataNasc = new javax.swing.JTextField();
        jLabelImagemUsuario = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelDataDeNascimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraPrincipal.setBackground(new java.awt.Color(31, 31, 31));
        jPanelBarraPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelBtnInicio.setBackground(new java.awt.Color(78, 78, 78));
        JPanelBtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanelBtnInicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JPanelBtnInicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JPanelBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseExited(evt);
            }
        });
        JPanelBtnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/casa.png"))); // NOI18N
        JPanelBtnInicio.add(jLabelIconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloInicio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloInicio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloInicio.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInicio.setText("Início");
        JPanelBtnInicio.add(jLabelTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 50));

        jPanelBarraPrincipal.add(JPanelBtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        jPanelBtnAgendamento.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBtnAgendamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnAgendamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnAgendamentoMouseExited(evt);
            }
        });
        jPanelBtnAgendamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/calendario.png"))); // NOI18N
        jPanelBtnAgendamento.add(jLabelIconCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloAgendamento.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloAgendamento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloAgendamento.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloAgendamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAgendamento.setText("Agendamento");
        jPanelBtnAgendamento.add(jLabelTituloAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 100, 50));

        jPanelBarraPrincipal.add(jPanelBtnAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 50));

        jPanelBtnPerfil.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBtnPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnPerfilMouseExited(evt);
            }
        });
        jPanelBtnPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/usuario.png"))); // NOI18N
        jPanelBtnPerfil.add(jLabelIconPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloPerfi.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloPerfi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloPerfi.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloPerfi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPerfi.setText("Perfil");
        jPanelBtnPerfil.add(jLabelTituloPerfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 32));

        jPanelBarraPrincipal.add(jPanelBtnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 50));

        jPanelBtnSair.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnSairMouseExited(evt);
            }
        });
        jPanelBtnSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/abertura-da-porta-aberta.png"))); // NOI18N
        jPanelBtnSair.add(jLabelIconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        jLabelTituloSair.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloSair.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloSair.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSair.setText("Sair");
        jPanelBtnSair.add(jLabelTituloSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 32));

        jPanelBarraPrincipal.add(jPanelBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 50));

        jPanelFundo.add(jPanelBarraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 530));

        jPanelBarraPanel.setBackground(new java.awt.Color(120, 120, 120));
        jPanelBarraPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelBarraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");
        jPanelBarraPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 100, -1));

        jPanelFundo.add(jPanelBarraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 90));

        jTabbedPaneAbas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPaneAbasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanelInicio.setEnabled(false);
        jPanelInicio.setPreferredSize(new java.awt.Dimension(628, 445));

        jTextAreaAgendado.setEditable(false);
        jTextAreaAgendado.setColumns(20);
        jTextAreaAgendado.setRows(5);
        jTextAreaAgendado.setText("Não há horário marcado.");
        jScrollPaneAgendado.setViewportView(jTextAreaAgendado);

        jLabelNovoAgendamento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelNovoAgendamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovoAgendamento.setText("Novo Agendamento");

        jButtonNovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnNovoAgendamentoLayout = new javax.swing.GroupLayout(jPanelBtnNovoAgendamento);
        jPanelBtnNovoAgendamento.setLayout(jPanelBtnNovoAgendamentoLayout);
        jPanelBtnNovoAgendamentoLayout.setHorizontalGroup(
            jPanelBtnNovoAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNovoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonNovoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelBtnNovoAgendamentoLayout.setVerticalGroup(
            jPanelBtnNovoAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnNovoAgendamentoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelNovoAgendamento)
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jButtonNovoAgendamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneAgendado)
                    .addComponent(jPanelBtnNovoAgendamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(jScrollPaneAgendado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jPanelBtnNovoAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPaneAbas.addTab("tab2", jPanelInicio);

        jPanelAgendamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelAgendamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButtonMarcar.setText("Marcar");
        jButtonMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMarcarActionPerformed(evt);
            }
        });

        jComboBoxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFuncionarioActionPerformed(evt);
            }
        });

        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });

        jSelecionaData.setToolTipText("");
        jSelecionaData.setDateFormatString("dd/MM/YYYY");
        jSelecionaData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSelecionaDataPropertyChange(evt);
            }
        });

        jComboBoxHorarios.setToolTipText("");
        jComboBoxHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgendamentoLayout = new javax.swing.GroupLayout(jPanelAgendamento);
        jPanelAgendamento.setLayout(jPanelAgendamentoLayout);
        jPanelAgendamentoLayout.setHorizontalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jButtonMarcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxServico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSelecionaData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxHorarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanelAgendamentoLayout.setVerticalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBoxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSelecionaData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPaneAbas.addTab("tab1", jPanelAgendamento);

        jTextFieldNome.setEditable(false);

        jTextFieldEmail.setEditable(false);

        jTextFieldTelefone.setEditable(false);

        jTextFieldDataNasc.setEditable(false);

        jLabelImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/imagem-do-usuario-com-fundo-preto (1).png"))); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelEmail.setText("Email");

        jLabelTelefone.setText("Telefone");

        jLabelDataDeNascimento.setText("Data de Nascimento");

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addComponent(jLabelNome)
                    .addComponent(jLabelTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataDeNascimento)
                    .addComponent(jLabelEmail)
                    .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDataNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabelImagemUsuario)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelImagemUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jTabbedPaneAbas.addTab("tab3", jPanelPerfil);

        jPanelFundo.add(jTabbedPaneAbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 620, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherComboBoxHorarios() {
        controller.implementarHorarioDisponiveis();
    }

    private void jButtonNovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoAgendamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNovoAgendamentoActionPerformed

    private void jButtonMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMarcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMarcarActionPerformed

    private void JPanelBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseClicked

        // TODO add your handling code here:
        jTabbedPaneAbas.setSelectedIndex(0);
        controller.mostrarHorario(pessoa != null ? pessoa.getId() : 0);
        colorDefaultInicio = new Color(121,121,121);
        colorDefaultAgendamento = new Color(78,78,78);
        colorDefaultPerfil = new Color(78,78,78);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);
        

    }//GEN-LAST:event_JPanelBtnInicioMouseClicked

    private void jPanelBtnAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnAgendamentoMouseClicked
        // TODO add your handling code here:
        jTabbedPaneAbas.setSelectedIndex(1);
        colorDefaultInicio = new Color(78,78,78);
        colorDefaultAgendamento = new Color(121,121,121);
        colorDefaultPerfil = new Color(78,78,78);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);
    }//GEN-LAST:event_jPanelBtnAgendamentoMouseClicked

    private void JPanelBtnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseEntered
        // TODO add your handling code here:
        JPanelBtnInicio.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_JPanelBtnInicioMouseEntered

    private void JPanelBtnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseExited
        // TODO add your handling code here:
        JPanelBtnInicio.setBackground(colorDefaultInicio);
    }//GEN-LAST:event_JPanelBtnInicioMouseExited

    private void jPanelBtnAgendamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnAgendamentoMouseExited
        // TODO add your handling code here:
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
    }//GEN-LAST:event_jPanelBtnAgendamentoMouseExited

    private void jPanelBtnAgendamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnAgendamentoMouseEntered
        // TODO add your handling code here:
        jPanelBtnAgendamento.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnAgendamentoMouseEntered

    private void jPanelBtnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPerfilMouseEntered
        // TODO add your handling code here:
        jPanelBtnPerfil.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnPerfilMouseEntered

    private void jPanelBtnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPerfilMouseExited
        // TODO add your handling code here:
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);
    }//GEN-LAST:event_jPanelBtnPerfilMouseExited

    private void jPanelBtnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnSairMouseEntered
        // TODO add your handling code here:
        jPanelBtnSair.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnSairMouseEntered

    private void jPanelBtnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnSairMouseExited
        // TODO add your handling code here:
        jPanelBtnSair.setBackground(new Color(78, 78, 78));
    }//GEN-LAST:event_jPanelBtnSairMouseExited

    private void JPanelBtnInicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JPanelBtnInicioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JPanelBtnInicioAncestorAdded

    private void jPanelAgendamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelAgendamentoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAgendamentoAncestorAdded

    private void jTabbedPaneAbasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPaneAbasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneAbasAncestorAdded
 
    private void jComboBoxHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHorariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHorariosActionPerformed

    private void jPanelBtnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPerfilMouseClicked

        jTabbedPaneAbas.setSelectedIndex(2);
        try{
            controller.atualizarPerfil(pessoa);
        }catch(Exception e){
            System.out.println("Erro: " + e.getMessage());
        }
        colorDefaultInicio = new Color(78,78,78);
        colorDefaultAgendamento = new Color(78,78,78);
        colorDefaultPerfil = new Color(121,121,121);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnAgendamento.setBackground(colorDefaultAgendamento);
        jPanelBtnPerfil.setBackground(colorDefaultPerfil);
        
    }//GEN-LAST:event_jPanelBtnPerfilMouseClicked

    private void jComboBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFuncionarioActionPerformed
        Pessoa funcionarioSelecionado = (Pessoa) jComboBoxFuncionario.getSelectedItem();
    
        if (funcionarioSelecionado != null && funcionarioSelecionado.getId() != 0) {  
            jSelecionaData.setEnabled(true);
        }else{
            jSelecionaData.setEnabled(false);
            jSelecionaData.setDate(null);
        }
    }//GEN-LAST:event_jComboBoxFuncionarioActionPerformed

    private void jSelecionaDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSelecionaDataPropertyChange
        if ("date".equals(evt.getPropertyName())) {  
            Date dataSelecionada = (Date) evt.getNewValue(); 
            if (dataSelecionada == null) {
                return; 
            }
            Calendar hoje = Calendar.getInstance();
            hoje.add(Calendar.DAY_OF_YEAR, 1);  
            if (dataSelecionada.before(hoje.getTime())){    
                jComboBoxHorarios.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Por favor, selecione uma data a partir de amanhã.", "Data Inválida", JOptionPane.ERROR_MESSAGE);
                
                
            }else{
                jComboBoxHorarios.setEnabled(true);
            }  
        }
    }//GEN-LAST:event_jSelecionaDataPropertyChange

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    public JComboBox<String> getjComboBoxHorarios() {
        return jComboBoxHorarios;
    }

    public void setjComboBoxHorarios(JComboBox<String> jComboBoxHorarios) {
        this.jComboBoxHorarios = jComboBoxHorarios;
    }

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewCliente cliente = new ViewCliente();
                cliente.setarCliente();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBtnInicio;
    private javax.swing.JButton jButtonMarcar;
    private javax.swing.JButton jButtonNovoAgendamento;
    private javax.swing.JComboBox<Pessoa> jComboBoxFuncionario;
    private javax.swing.JComboBox<String> jComboBoxHorarios;
    private javax.swing.JComboBox<Servico> jComboBoxServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDataDeNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelIconCalendario;
    private javax.swing.JLabel jLabelIconInicio;
    private javax.swing.JLabel jLabelIconPerfil;
    private javax.swing.JLabel jLabelIconSair;
    private javax.swing.JLabel jLabelImagemUsuario;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoAgendamento;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTituloAgendamento;
    private javax.swing.JLabel jLabelTituloInicio;
    private javax.swing.JLabel jLabelTituloPerfi;
    private javax.swing.JLabel jLabelTituloSair;
    private javax.swing.JPanel jPanelAgendamento;
    private javax.swing.JPanel jPanelBarraPanel;
    private javax.swing.JPanel jPanelBarraPrincipal;
    private javax.swing.JPanel jPanelBtnAgendamento;
    private javax.swing.JPanel jPanelBtnNovoAgendamento;
    private javax.swing.JPanel jPanelBtnPerfil;
    private javax.swing.JPanel jPanelBtnSair;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneAgendado;
    private com.toedter.calendar.JDateChooser jSelecionaData;
    private javax.swing.JTabbedPane jTabbedPaneAbas;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaAgendado;
    private javax.swing.JTextField jTextFieldDataNasc;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables

    public void setarCliente() {
        this.setLocationRelativeTo(null);
        this.setSize(850, 530);
        this.setResizable(false);
        this.setVisible(true);
        controller.mostrarHorario(pessoa != null ? pessoa.getId() : 0);
        controller.setarComboBoxFuncionario();
        controller.setarComboBoxServico();
    }

    public JTextArea getjTextArea1() {
        return jTextAreaAgendado;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextAreaAgendado = jTextArea1;
    }

    public JComboBox<Pessoa> getjComboBoxFuncionario() {
        return jComboBoxFuncionario;
    }

    public JTextField getjTextFieldDataNasc() {
        return jTextFieldDataNasc;
    }

    public void setjTextFieldDataNasc(JTextField jTextFieldDataNasc) {
        this.jTextFieldDataNasc = jTextFieldDataNasc;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JTextField getjTextFieldTelefone() {
        return jTextFieldTelefone;
    }

    public void setjTextFieldTelefone(JTextField jTextFieldTelefone) {
        this.jTextFieldTelefone = jTextFieldTelefone;
    }

    public void setjComboBoxFuncionario(JComboBox<Pessoa> jComboBoxFuncionario) {
        this.jComboBoxFuncionario = jComboBoxFuncionario;
    }

    public JComboBox<Servico> getjComboBoxServico() {
        return jComboBoxServico;
    }

    public void setjComboBoxServico(JComboBox<Servico> jComboBoxServico) {
        this.jComboBoxServico = jComboBoxServico;
    }

    public JDateChooser getjSelecionaData() {
        return jSelecionaData;
    }

    public void setjSelecionaData(JDateChooser jSelecionaData) {
        this.jSelecionaData = jSelecionaData;
    }

//    private List<String> consultarHorariosIndisponiveis(String dataSelecionada) {
//        List<String> horariosIndisponiveis = new ArrayList<>();
//        // Implementação de leitura do CSV para verificar horários
//        return horariosIndisponiveis;
//    }
//
//    private void adicionarHorarioIndisponivel(String dataSelecionada, String horarioSelecionado, String servicoSelecionado, String funcionarioSelecionado, String clienteSelecionado) {
//       // Implementação de escrita no CSV
//    }
    
    
}
