/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import BDO.PessoaBanco;
import BDO.ServicoBanco;
import Controller.AdminController;
import Controller.ClienteController;
import Model.Pessoa;
import Model.Servico;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;

public class ViewAdmin extends javax.swing.JFrame {
    private AdminController controller;
    private final Pessoa admin;
    private Color colorDefaultInicio = new Color(121, 121, 121);
    private Color colorDefaultCortes = new Color(121, 121, 121);
    private Color colorDefaultPessoas = new Color(121, 121, 121);

    public ViewAdmin(Pessoa admin) {
        this.admin = admin;
        initComponents();
        this.controller = new AdminController(this);
    }

    public ViewAdmin() {
        initComponents();
        this.controller = new AdminController(this);
        this.admin = null;

    }

    public JTable getjTableClientes() {
        return jTableClientes;
    }

    public void setjTableClientes(JTable jTableClientes) {
        this.jTableClientes = jTableClientes;
    }

    public JTable getjTableCortes() {
        return jTableCortes;
    }

    public void setjTableCortes(JTable jTableCortes) {
        this.jTableCortes = jTableCortes;
    }

    public JTable getjTableFuncionarios() {
        return jTableFuncionarios;
    }

    public void setjTableFuncionarios(JTable jTableFuncionarios) {
        this.jTableFuncionarios = jTableFuncionarios;
    }

    public JTextField getjTextFieldDataNascimento() {
        return jTextFieldDataNascimento;
    }

    public void setjTextFieldDataNascimento(JTextField jTextFieldDataNascimento) {
        this.jTextFieldDataNascimento = jTextFieldDataNascimento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        jPanelBarraPrincipal = new javax.swing.JPanel();
        JPanelBtnInicio = new javax.swing.JPanel();
        jLabelIconInicio = new javax.swing.JLabel();
        jLabelTituloInicio = new javax.swing.JLabel();
        jPanelBtnCortes = new javax.swing.JPanel();
        jLabelIconCalendario = new javax.swing.JLabel();
        jLabelTituloAgendamento = new javax.swing.JLabel();
        jPanelBtnPessoas = new javax.swing.JPanel();
        jLabelIconPerfil = new javax.swing.JLabel();
        jLabelTituloPerfi = new javax.swing.JLabel();
        jPanelBtnSair = new javax.swing.JPanel();
        jLabelIconSair = new javax.swing.JLabel();
        jLabelTituloSair = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelIconPerfil1 = new javax.swing.JLabel();
        jLabelTituloPerfi2 = new javax.swing.JLabel();
        jPanelBarraPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPanePessoas = new javax.swing.JTabbedPane();
        jPanelInicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelAgendamento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCortes = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanelPessoas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButtonEditarCli = new javax.swing.JButton();
        jPanelAdicionaFuncionario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelAdicionaCorte = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextFieldNomeCorte = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldValorCorte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTempoCorte = new javax.swing.JTextField();
        jPanelFuncionarios = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraPrincipal.setBackground(new java.awt.Color(31, 31, 31));
        jPanelBarraPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelBtnInicio.setBackground(new java.awt.Color(78, 78, 78));
        JPanelBtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanelBtnInicio.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                JPanelBtnInicioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JPanelBtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPanelBtnInicioMouseExited(evt);
            }
        });
        JPanelBtnInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/casa.png"))); // NOI18N
        JPanelBtnInicio.add(jLabelIconInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloInicio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloInicio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloInicio.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInicio.setText("Início");
        JPanelBtnInicio.add(jLabelTituloInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 50));

        jPanelBarraPrincipal.add(JPanelBtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 50));

        jPanelBtnCortes.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnCortes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnCortes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBtnCortesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnCortesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnCortesMouseExited(evt);
            }
        });
        jPanelBtnCortes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconCalendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/calendario.png"))); // NOI18N
        jPanelBtnCortes.add(jLabelIconCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloAgendamento.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloAgendamento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloAgendamento.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloAgendamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloAgendamento.setText("Cortes");
        jPanelBtnCortes.add(jLabelTituloAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 100, 50));

        jPanelBarraPrincipal.add(jPanelBtnCortes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        jPanelBtnPessoas.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnPessoas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBtnPessoasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnPessoasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnPessoasMouseExited(evt);
            }
        });
        jPanelBtnPessoas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/usuario.png"))); // NOI18N
        jPanelBtnPessoas.add(jLabelIconPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelTituloPerfi.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloPerfi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloPerfi.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloPerfi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPerfi.setText("Clientes");
        jPanelBtnPessoas.add(jLabelTituloPerfi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 60, 32));

        jPanelBarraPrincipal.add(jPanelBtnPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 50));

        jPanelBtnSair.setBackground(new java.awt.Color(78, 78, 78));
        jPanelBtnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBtnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBtnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBtnSairMouseExited(evt);
            }
        });
        jPanelBtnSair.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIconSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/abertura-da-porta-aberta.png"))); // NOI18N
        jPanelBtnSair.add(jLabelIconSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        jLabelTituloSair.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloSair.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloSair.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSair.setText("Sair");
        jPanelBtnSair.add(jLabelTituloSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 32));

        jPanelBarraPrincipal.add(jPanelBtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 50));

        jPanel1.setBackground(new java.awt.Color(78, 78, 78));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabelIconPerfil1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIconPerfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/usuario.png"))); // NOI18N

        jLabelTituloPerfi2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTituloPerfi2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabelTituloPerfi2.setForeground(new java.awt.Color(235, 235, 235));
        jLabelTituloPerfi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPerfi2.setText("Funcionarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelIconPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabelTituloPerfi2)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelIconPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloPerfi2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBarraPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 50));

        jPanelFundo.add(jPanelBarraPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 530));

        jPanelBarraPanel.setBackground(new java.awt.Color(120, 120, 120));
        jPanelBarraPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelBarraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(235, 235, 235));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Início");
        jPanelBarraPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 90));

        jPanelFundo.add(jPanelBarraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 620, 90));

        jTabbedPanePessoas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPanePessoasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanelInicio.setEnabled(false);
        jPanelInicio.setPreferredSize(new java.awt.Dimension(628, 445));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Bem vindo Adiministrador");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPanePessoas.addTab("Inicio", jPanelInicio);

        jPanelAgendamento.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanelAgendamentoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTableCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCortes);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setText("Cortes");

        jToggleButton1.setText("Remover Corte");

        jToggleButton2.setText("Editar Corte");

        jToggleButton3.setText("Novo Corte");

        javax.swing.GroupLayout jPanelAgendamentoLayout = new javax.swing.GroupLayout(jPanelAgendamento);
        jPanelAgendamento.setLayout(jPanelAgendamentoLayout);
        jPanelAgendamentoLayout.setHorizontalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanelAgendamentoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jToggleButton2)
                        .addGap(64, 64, 64)
                        .addComponent(jToggleButton1)
                        .addGap(76, 76, 76)
                        .addComponent(jToggleButton3)
                        .addContainerGap())))
        );
        jPanelAgendamentoLayout.setVerticalGroup(
            jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgendamentoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelAgendamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3))
                .addGap(25, 25, 25))
        );

        jTabbedPanePessoas.addTab("Cortes", jPanelAgendamento);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableClientes);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Clientes");

        jButton4.setText("Remover ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButtonEditarCli.setText("Editar");
        jButtonEditarCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarCliMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPessoasLayout = new javax.swing.GroupLayout(jPanelPessoas);
        jPanelPessoas.setLayout(jPanelPessoasLayout);
        jPanelPessoasLayout.setHorizontalGroup(
            jPanelPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPessoasLayout.createSequentialGroup()
                .addGroup(jPanelPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPessoasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                    .addGroup(jPanelPessoasLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPessoasLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButtonEditarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanelPessoasLayout.setVerticalGroup(
            jPanelPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPessoasLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButtonEditarCli))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPanePessoas.addTab("Clientes", jPanelPessoas);

        jLabel6.setText("Nome");

        jLabel7.setText("Data Nascimento");

        jLabel8.setText("Telefone");

        jLabel9.setText("Email");

        jTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneActionPerformed(evt);
            }
        });

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar Novo Funcionario");

        javax.swing.GroupLayout jPanelAdicionaFuncionarioLayout = new javax.swing.GroupLayout(jPanelAdicionaFuncionario);
        jPanelAdicionaFuncionario.setLayout(jPanelAdicionaFuncionarioLayout);
        jPanelAdicionaFuncionarioLayout.setHorizontalGroup(
            jPanelAdicionaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaFuncionarioLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanelAdicionaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldEmail)
                    .addComponent(jTextFieldTelefone)
                    .addComponent(jTextFieldDataNascimento)
                    .addComponent(jTextFieldNome))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanelAdicionaFuncionarioLayout.setVerticalGroup(
            jPanelAdicionaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaFuncionarioLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPanePessoas.addTab("Adiciona Funcionario", jPanelAdicionaFuncionario);

        jLabel5.setText("Nome ");

        jButton2.setText("Novo Corte");

        jLabel10.setText("Valor");

        jLabel11.setText("Tempo (1 = 15 minutos)");

        javax.swing.GroupLayout jPanelAdicionaCorteLayout = new javax.swing.GroupLayout(jPanelAdicionaCorte);
        jPanelAdicionaCorte.setLayout(jPanelAdicionaCorteLayout);
        jPanelAdicionaCorteLayout.setHorizontalGroup(
            jPanelAdicionaCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaCorteLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanelAdicionaCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeCorte)
                    .addComponent(jTextFieldValorCorte)
                    .addComponent(jTextFieldTempoCorte))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanelAdicionaCorteLayout.setVerticalGroup(
            jPanelAdicionaCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionaCorteLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNomeCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldValorCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldTempoCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        jTabbedPanePessoas.addTab("Adiciona Corte", jPanelAdicionaCorte);

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane5.setViewportView(jTableFuncionarios);
        if (jTableFuncionarios.getColumnModel().getColumnCount() > 0) {
            jTableFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            jTableFuncionarios.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Funcionarios");

        jButtonEditar.setText("Editar");
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
        });

        jButtonRemover.setText("Remover");

        jButtonNovo.setText("Novo");

        javax.swing.GroupLayout jPanelFuncionariosLayout = new javax.swing.GroupLayout(jPanelFuncionarios);
        jPanelFuncionarios.setLayout(jPanelFuncionariosLayout);
        jPanelFuncionariosLayout.setHorizontalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                .addGroup(jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                    .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                        .addGroup(jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(jLabel13))
                            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFuncionariosLayout.setVerticalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRemover)
                    .addComponent(jButtonNovo))
                .addContainerGap())
        );

        jTabbedPanePessoas.addTab("Funcionarios", jPanelFuncionarios);

        jPanelFundo.add(jTabbedPanePessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 620, 480));

        getContentPane().add(jPanelFundo, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPanelBtnInicioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_JPanelBtnInicioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_JPanelBtnInicioAncestorAdded

    private void JPanelBtnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseClicked

        // TODO add your handling code here:
        jTabbedPanePessoas.setSelectedIndex(0);
        colorDefaultInicio = new Color(121, 121, 121);
        colorDefaultCortes = new Color(78, 78, 78);
        colorDefaultPessoas = new Color(78, 78, 78);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnCortes.setBackground(colorDefaultCortes);
        jPanelBtnPessoas.setBackground(colorDefaultPessoas);


    }//GEN-LAST:event_JPanelBtnInicioMouseClicked

    private void JPanelBtnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseEntered
        // TODO add your handling code here:
        JPanelBtnInicio.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_JPanelBtnInicioMouseEntered

    private void JPanelBtnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBtnInicioMouseExited
        
        JPanelBtnInicio.setBackground(colorDefaultInicio);
    }//GEN-LAST:event_JPanelBtnInicioMouseExited

    private void jPanelBtnCortesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnCortesMouseClicked
        // TODO add your handling code here:

        jTabbedPanePessoas.setSelectedIndex(1);
        colorDefaultInicio = new Color(78, 78, 78);
        colorDefaultCortes = new Color(121, 121, 121);
        colorDefaultPessoas = new Color(78, 78, 78);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnCortes.setBackground(colorDefaultCortes);
        jPanelBtnPessoas.setBackground(colorDefaultPessoas);
    }//GEN-LAST:event_jPanelBtnCortesMouseClicked

    private void jPanelBtnCortesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnCortesMouseEntered
        // TODO add your handling code here:
        jPanelBtnCortes.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnCortesMouseEntered

    private void jPanelBtnCortesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnCortesMouseExited
        // TODO add your handling code here:
        jPanelBtnCortes.setBackground(colorDefaultCortes);
    }//GEN-LAST:event_jPanelBtnCortesMouseExited

    private void jPanelBtnPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPessoasMouseClicked

        jTabbedPanePessoas.setSelectedIndex(2);
        colorDefaultInicio = new Color(78, 78, 78);
        colorDefaultCortes = new Color(78, 78, 78);
        colorDefaultPessoas = new Color(121, 121, 121);
        JPanelBtnInicio.setBackground(colorDefaultInicio);
        jPanelBtnCortes.setBackground(colorDefaultCortes);
        jPanelBtnPessoas.setBackground(colorDefaultPessoas);

    }//GEN-LAST:event_jPanelBtnPessoasMouseClicked

    private void jPanelBtnPessoasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPessoasMouseEntered
        // TODO add your handling code here:
        jPanelBtnPessoas.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnPessoasMouseEntered

    private void jPanelBtnPessoasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnPessoasMouseExited
        // TODO add your handling code here:
        jPanelBtnPessoas.setBackground(colorDefaultPessoas);
    }//GEN-LAST:event_jPanelBtnPessoasMouseExited

    private void jPanelBtnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnSairMouseEntered
        // TODO add your handling code here:
        jPanelBtnSair.setBackground(new Color(121, 121, 121));
    }//GEN-LAST:event_jPanelBtnSairMouseEntered

    private void jPanelBtnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBtnSairMouseExited
        // TODO add your handling code here:
        jPanelBtnSair.setBackground(new Color(78, 78, 78));
    }//GEN-LAST:event_jPanelBtnSairMouseExited

    private void jPanelAgendamentoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanelAgendamentoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelAgendamentoAncestorAdded

    private void jTabbedPanePessoasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPanePessoasAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPanePessoasAncestorAdded

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        jTabbedPanePessoas.setSelectedIndex(5);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        // TODO add your handling code here:
        controller.editarFuncionario();
    }//GEN-LAST:event_jButtonEditarMouseClicked

    private void jButtonEditarCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarCliMouseClicked
        // TODO add your handling code here:
        controller.editarCliente();
    }//GEN-LAST:event_jButtonEditarCliMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controller.removerCliente();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAdmin view = new ViewAdmin();
                view.setarAdmin();
                view.atualizaTabela();
                
            }
        });
        
    }
    public void setarAdmin(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.atualizaTabela();
        this.setVisible(true); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBtnInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEditarCli;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIconCalendario;
    private javax.swing.JLabel jLabelIconInicio;
    private javax.swing.JLabel jLabelIconPerfil;
    private javax.swing.JLabel jLabelIconPerfil1;
    private javax.swing.JLabel jLabelIconSair;
    private javax.swing.JLabel jLabelTituloAgendamento;
    private javax.swing.JLabel jLabelTituloInicio;
    private javax.swing.JLabel jLabelTituloPerfi;
    private javax.swing.JLabel jLabelTituloPerfi2;
    private javax.swing.JLabel jLabelTituloSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAdicionaCorte;
    private javax.swing.JPanel jPanelAdicionaFuncionario;
    private javax.swing.JPanel jPanelAgendamento;
    private javax.swing.JPanel jPanelBarraPanel;
    private javax.swing.JPanel jPanelBarraPrincipal;
    private javax.swing.JPanel jPanelBtnCortes;
    private javax.swing.JPanel jPanelBtnPessoas;
    private javax.swing.JPanel jPanelBtnSair;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelPessoas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPanePessoas;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableCortes;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeCorte;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTempoCorte;
    private javax.swing.JTextField jTextFieldValorCorte;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables

    public void atualizaTabela(){
        controller.adicionaCamposTabelaCortes(); 
        controller.adicionaCamposFuncionarios();
        controller.adicionaCamposClientes();
    }
//    public void atualizaTabela(){
//        controller.adicionaCamposTabelaCortes();
//    }
//    
//    private void initTableListenersConfirmados() {
//        TabelaConfirmados.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {        
//            if (!event.getValueIsAdjusting()) {
//                int selectedRow = TabelaConfirmados.getSelectedRow();
//                
//                if (selectedRow >= 0) {
//                    Remover.setEnabled(true);
//                    Editar.setEnabled(true);
//                    Confirmar.setEnabled(false);
//                    Rejeitar.setEnabled(false);
//                    TabelaPendentes.clearSelection();
//                    controller.atualizaCamposConfirmados();
//                    
//                }
//            }
//        });
//        
    }