/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


public class ViewAdmin extends javax.swing.JFrame {


    public ViewAdmin() {
        initComponents();
        jPanel3Lateral.setVisible(false); 
        jPanel3Lateral1.setVisible(false); 
        jPanelEditarCorte.setVisible(false); 
        jPanelAdcionaCorte.setVisible(false); 
        jPanelLateralBotoes.setVisible(false); 
        jPanelEditarFuncionario.setVisible(false); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDosBotoesP = new javax.swing.JPanel();
        jButtonCortes = new javax.swing.JButton();
        jButtonFuncionarios = new javax.swing.JButton();
        jPanelPrincipalLateralCortes = new javax.swing.JPanel();
        jPanelLateralBotoes = new javax.swing.JPanel();
        jButtonEditaCorte = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3Lateral = new javax.swing.JPanel();
        jPanelEditarCorte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelAdcionaCorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelDosBotoesP1 = new javax.swing.JPanel();
        jButtonCortes1 = new javax.swing.JButton();
        jButtonFuncionarios1 = new javax.swing.JButton();
        jPanelPrincipalLateralFuncionario = new javax.swing.JPanel();
        jPanelLateralBotoes1 = new javax.swing.JPanel();
        jButtonEditaCorte1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3Lateral1 = new javax.swing.JPanel();
        jPanelEditarFuncionario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelAdcionaFuncionario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jButtonCortes.setText("Cortes");
        jButtonCortes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCortesActionPerformed(evt);
            }
        });

        jButtonFuncionarios.setText("Funcionarios");
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDosBotoesPLayout = new javax.swing.GroupLayout(jPanelDosBotoesP);
        jPanelDosBotoesP.setLayout(jPanelDosBotoesPLayout);
        jPanelDosBotoesPLayout.setHorizontalGroup(
            jPanelDosBotoesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCortes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDosBotoesPLayout.setVerticalGroup(
            jPanelDosBotoesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosBotoesPLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButtonCortes)
                .addGap(28, 28, 28)
                .addComponent(jButtonFuncionarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEditaCorte.setText("Editar Cortes");
        jButtonEditaCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaCorteActionPerformed(evt);
            }
        });

        jButton2.setText("Adcionar Cortes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralBotoesLayout = new javax.swing.GroupLayout(jPanelLateralBotoes);
        jPanelLateralBotoes.setLayout(jPanelLateralBotoesLayout);
        jPanelLateralBotoesLayout.setHorizontalGroup(
            jPanelLateralBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonEditaCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLateralBotoesLayout.setVerticalGroup(
            jPanelLateralBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralBotoesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButtonEditaCorte)
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jPanel3Lateral.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Editando O Corte");

        javax.swing.GroupLayout jPanelEditarCorteLayout = new javax.swing.GroupLayout(jPanelEditarCorte);
        jPanelEditarCorte.setLayout(jPanelEditarCorteLayout);
        jPanelEditarCorteLayout.setHorizontalGroup(
            jPanelEditarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarCorteLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanelEditarCorteLayout.setVerticalGroup(
            jPanelEditarCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarCorteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel2)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanel3Lateral.add(jPanelEditarCorte, "card2");

        jLabel1.setText("Adicionando corte");

        javax.swing.GroupLayout jPanelAdcionaCorteLayout = new javax.swing.GroupLayout(jPanelAdcionaCorte);
        jPanelAdcionaCorte.setLayout(jPanelAdcionaCorteLayout);
        jPanelAdcionaCorteLayout.setHorizontalGroup(
            jPanelAdcionaCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdcionaCorteLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanelAdcionaCorteLayout.setVerticalGroup(
            jPanelAdcionaCorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdcionaCorteLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel3Lateral.add(jPanelAdcionaCorte, "card3");

        javax.swing.GroupLayout jPanelPrincipalLateralCortesLayout = new javax.swing.GroupLayout(jPanelPrincipalLateralCortes);
        jPanelPrincipalLateralCortes.setLayout(jPanelPrincipalLateralCortesLayout);
        jPanelPrincipalLateralCortesLayout.setHorizontalGroup(
            jPanelPrincipalLateralCortesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLateralCortesLayout.createSequentialGroup()
                .addComponent(jPanelLateralBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3Lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPrincipalLateralCortesLayout.setVerticalGroup(
            jPanelPrincipalLateralCortesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLateralBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3Lateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelDosBotoesP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipalLateralCortes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDosBotoesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPrincipalLateralCortes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, "card2");

        jButtonCortes1.setText("Cortes");
        jButtonCortes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCortes1ActionPerformed(evt);
            }
        });

        jButtonFuncionarios1.setText("Funcionarios");
        jButtonFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDosBotoesP1Layout = new javax.swing.GroupLayout(jPanelDosBotoesP1);
        jPanelDosBotoesP1.setLayout(jPanelDosBotoesP1Layout);
        jPanelDosBotoesP1Layout.setHorizontalGroup(
            jPanelDosBotoesP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCortes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonFuncionarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelDosBotoesP1Layout.setVerticalGroup(
            jPanelDosBotoesP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosBotoesP1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButtonCortes1)
                .addGap(28, 28, 28)
                .addComponent(jButtonFuncionarios1)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jButtonEditaCorte1.setText("Editar Fum");
        jButtonEditaCorte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaCorte1ActionPerformed(evt);
            }
        });

        jButton3.setText("Adcionar Fum");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLateralBotoes1Layout = new javax.swing.GroupLayout(jPanelLateralBotoes1);
        jPanelLateralBotoes1.setLayout(jPanelLateralBotoes1Layout);
        jPanelLateralBotoes1Layout.setHorizontalGroup(
            jPanelLateralBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonEditaCorte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLateralBotoes1Layout.setVerticalGroup(
            jPanelLateralBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLateralBotoes1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButtonEditaCorte1)
                .addGap(52, 52, 52)
                .addComponent(jButton3)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanel3Lateral1.setLayout(new java.awt.CardLayout());

        jLabel3.setText("TesteEditaCorte");

        javax.swing.GroupLayout jPanelEditarFuncionarioLayout = new javax.swing.GroupLayout(jPanelEditarFuncionario);
        jPanelEditarFuncionario.setLayout(jPanelEditarFuncionarioLayout);
        jPanelEditarFuncionarioLayout.setHorizontalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarFuncionarioLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanelEditarFuncionarioLayout.setVerticalGroup(
            jPanelEditarFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarFuncionarioLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel3)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        jPanel3Lateral1.add(jPanelEditarFuncionario, "card2");

        jLabel4.setText("TesteFuncionario");

        javax.swing.GroupLayout jPanelAdcionaFuncionarioLayout = new javax.swing.GroupLayout(jPanelAdcionaFuncionario);
        jPanelAdcionaFuncionario.setLayout(jPanelAdcionaFuncionarioLayout);
        jPanelAdcionaFuncionarioLayout.setHorizontalGroup(
            jPanelAdcionaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdcionaFuncionarioLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelAdcionaFuncionarioLayout.setVerticalGroup(
            jPanelAdcionaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdcionaFuncionarioLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel4)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jPanel3Lateral1.add(jPanelAdcionaFuncionario, "card3");

        javax.swing.GroupLayout jPanelPrincipalLateralFuncionarioLayout = new javax.swing.GroupLayout(jPanelPrincipalLateralFuncionario);
        jPanelPrincipalLateralFuncionario.setLayout(jPanelPrincipalLateralFuncionarioLayout);
        jPanelPrincipalLateralFuncionarioLayout.setHorizontalGroup(
            jPanelPrincipalLateralFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLateralFuncionarioLayout.createSequentialGroup()
                .addComponent(jPanelLateralBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3Lateral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelPrincipalLateralFuncionarioLayout.setVerticalGroup(
            jPanelPrincipalLateralFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLateralBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3Lateral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelDosBotoesP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipalLateralFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDosBotoesP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPrincipalLateralFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCortesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCortesActionPerformed
        // TODO add your handling code here:
        jPanelPrincipalLateralCortes.setVisible(true); 
        jPanelLateralBotoes.setVisible(true);
    }//GEN-LAST:event_jButtonCortesActionPerformed

    private void jButtonEditaCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaCorteActionPerformed
        // TODO add your handling code here:
        jPanelEditarCorte.setVisible(true);
        jPanel3Lateral.setVisible(true);
        jPanelAdcionaCorte.setVisible(false);
    }//GEN-LAST:event_jButtonEditaCorteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelEditarCorte.setVisible(false);
        jPanel3Lateral.setVisible(true);
        jPanelAdcionaCorte.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        // TODO add your handling code here:
        jPanelPrincipalLateralCortes.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanelPrincipalLateralFuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    private void jButtonCortes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCortes1ActionPerformed
        // TODO add your handling code here:
        jPanelPrincipalLateralFuncionario.setVisible(false);
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanelPrincipalLateralCortes.setVisible(true);
        
    }//GEN-LAST:event_jButtonCortes1ActionPerformed

    private void jButtonFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarios1ActionPerformed
        // TODO add your handling code here:
        jPanelPrincipalLateralFuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonFuncionarios1ActionPerformed

    private void jButtonEditaCorte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaCorte1ActionPerformed
        // TODO add your handling code here:
        jPanelEditarFuncionario.setVisible(false);
        jPanel3Lateral1.setVisible(true);
        jPanelAdcionaFuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonEditaCorte1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCortes;
    private javax.swing.JButton jButtonCortes1;
    private javax.swing.JButton jButtonEditaCorte;
    private javax.swing.JButton jButtonEditaCorte1;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonFuncionarios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3Lateral;
    private javax.swing.JPanel jPanel3Lateral1;
    private javax.swing.JPanel jPanelAdcionaCorte;
    private javax.swing.JPanel jPanelAdcionaFuncionario;
    private javax.swing.JPanel jPanelDosBotoesP;
    private javax.swing.JPanel jPanelDosBotoesP1;
    private javax.swing.JPanel jPanelEditarCorte;
    private javax.swing.JPanel jPanelEditarFuncionario;
    private javax.swing.JPanel jPanelLateralBotoes;
    private javax.swing.JPanel jPanelLateralBotoes1;
    private javax.swing.JPanel jPanelPrincipalLateralCortes;
    private javax.swing.JPanel jPanelPrincipalLateralFuncionario;
    // End of variables declaration//GEN-END:variables
}
